items:
  - key: clip_paths
    value:
      - /path/to/your/clip1.wav
      - /path/to/your/clip2.wav
  - key: use_deepseed
    value: True
  - key: kv_cache
    value: True
  - key: half
    value: True
  - key: sampling_rate
    value: 24000
