name: Just Helping Out
description: >
  We are working together on AI character development. The user will describe problems with the character 
  and the machine will offer up ideas to make the character more interesting and full. 

summary:
  user: true
  assistant: true
  description: >
    Create a list of the ideas we have already come up with.